### ISSUE TITLE
feat:리액트 웹ui 구성

### ISSUE THREAD

**Issue by Topadonijah** [kookmin-sw/capstone-2024-11#15]
- 피그마 xd 작성
- 메인 화면 리액트 구현

**Comment by wjsquddn** [comment]
1. 페이지 구성 완료
2. 페이지 메인 색상 정함
3. 로고 프로젝트 이름 정하기 완료

**Comment by wjsquddn** [comment]
1. 로고 디자인
2. 메인페이지 디자인 초안 작성 완료
피그마 주소 : 
https://www.figma.com/file/quvHn8MEYzXVVIDKn97h4L/capstondesign-11%EC%A1%B0?type=design&node-id=17%3A21&mode=design&t=HjwjGpW0Pwkeb1DY-1
